- name: download and unarchive terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes

- name: create link to /usr/bin
  file:
   src: "/usr/local/bin/terraform"
   dest: "/usr/bin/terraform"
   state: link
